/**
 * "Did Fondas write this?" — answered for a DPO without reading anyone's mail
 * (AI_ACT_PROMPTS.md A2).
 *
 *   npm run verify-ai-mark < body.txt
 *
 * Paste the body of a sent email into a file (or pipe it in). The script
 * hashes it the same way lib/ai-provenance.ts hashed the draft when Fondas
 * wrote it, and looks the hash up in emails.draft_sha256 and
 * checkin_chasers.draft_sha256.
 *
 * What a match means: this exact text is a draft Fondas generated — so it was
 * sent unedited. An edited reply will NOT match (the hash is of the draft, not
 * of what was sent); for those, the X-Fondas-AI header on the sent message
 * carries `ref=` (the first 16 hex of the draft's hash) and `edit=`.
 * `npm run verify-ai-mark -- --ref <16 hex>` looks that ref up instead.
 *
 * PRINTS ONLY: found or not, table, generated_at, model, prompt version and
 * edited. Never the body, the guest, an address or a subject — the output of
 * this script is meant to be pasted into a reply to a DPO.
 *
 * Reads via the service-role key (like verify-migrations), so it runs from a
 * trusted terminal only. Exits 0 when found, 1 when not, 2 on error.
 */

import { createClient } from "@supabase/supabase-js";

import { sha256 } from "../lib/ai-provenance";

try {
  process.loadEnvFile(".env.local");
} catch {
  // No .env.local — fall back to the ambient environment.
}

const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!url || !key) {
  console.error(
    "Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in .env.local."
  );
  process.exit(2);
}

const db = createClient(url, key, { auth: { persistSession: false } });

const TABLES = ["emails", "checkin_chasers"] as const;
const COLUMNS = "draft_generated_at, draft_model, draft_prompt_version, draft_edited";

interface Hit {
  draft_generated_at: string | null;
  draft_model: string | null;
  draft_prompt_version: string | null;
  draft_edited: boolean | null;
}

async function readStdin(): Promise<string> {
  const chunks: Buffer[] = [];
  for await (const chunk of process.stdin) chunks.push(chunk as Buffer);
  return Buffer.concat(chunks).toString("utf8");
}

/**
 * Mail clients add a trailing newline, and copy-paste turns CRLF into LF or
 * back. Drafts are stored trimmed, so the trimmed, LF-normalised text is the
 * likeliest match; the raw text is tried too, in case a draft kept its edges.
 */
function candidates(body: string): string[] {
  const lf = body.replace(/\r\n/g, "\n");
  return [...new Set([body, body.trim(), lf, lf.trim()])].filter(Boolean);
}

function report(table: string, hit: Hit): void {
  console.log("FOUND — this text was generated by Fondas.");
  console.log(`  table         ${table}`);
  console.log(`  generated_at  ${hit.draft_generated_at ?? "(not recorded)"}`);
  console.log(`  model         ${hit.draft_model ?? "(not recorded)"}`);
  console.log(`  prompt        ${hit.draft_prompt_version ?? "(not recorded)"}`);
  console.log(
    `  edited        ${
      hit.draft_edited === null ? "(not sent yet, or sent before 0025)" : hit.draft_edited
    }`
  );
}

async function main() {
  const refIndex = process.argv.indexOf("--ref");
  if (refIndex !== -1) {
    const ref = (process.argv[refIndex + 1] ?? "").toLowerCase();
    if (!/^[0-9a-f]{16}$/.test(ref)) {
      console.error("--ref takes the 16 hex characters from the X-Fondas-AI header.");
      process.exit(2);
    }
    for (const table of TABLES) {
      const { data, error } = await db
        .from(table)
        .select(COLUMNS)
        .like("draft_sha256", `${ref}%`)
        .limit(2);
      if (error) throw new Error(`${table}: ${error.message}`);
      if (data && data.length > 0) {
        report(table, data[0] as Hit);
        if (data.length > 1) console.log("  note          more than one draft shares this ref");
        process.exit(0);
      }
    }
    console.log("NOT FOUND — no Fondas draft has this ref.");
    process.exit(1);
  }

  const body = await readStdin();
  if (!body.trim()) {
    console.error("Pipe the email body in: npm run verify-ai-mark < body.txt");
    process.exit(2);
  }
  const hashes = candidates(body).map(sha256);

  for (const table of TABLES) {
    const { data, error } = await db
      .from(table)
      .select(COLUMNS)
      .in("draft_sha256", hashes)
      .limit(1);
    if (error) throw new Error(`${table}: ${error.message}`);
    if (data && data.length > 0) {
      report(table, data[0] as Hit);
      process.exit(0);
    }
  }

  console.log(
    "NOT FOUND — this exact text is not a stored Fondas draft. If the sent\n" +
      "message carries an X-Fondas-AI header, it started as one and was edited;\n" +
      "look its ref up with: npm run verify-ai-mark -- --ref <16 hex>"
  );
  process.exit(1);
}

main().catch((err: Error) => {
  // The message is ours or the database's; it never contains the body.
  console.error(`verify-ai-mark: ${err.message}`);
  process.exit(2);
});
